# Generated by Django 4.0.4 on 2022-06-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/users/profiles'),
        ),
    ]
