# Generated by Django 4.0.4 on 2022-06-23 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='tages',
            new_name='tags',
        ),
    ]
