# Generated by Django 4.0.4 on 2022-06-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_posts_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
    ]
