# Generated by Django 4.0.4 on 2022-06-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_posts_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/blog/post'),
        ),
    ]
