# Generated by Django 4.0.4 on 2022-06-25 17:20

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('Blog', '0004_comments_is_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='is_publish',
            new_name='is_published',
        ),
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Blog.category'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
