# Generated by Django 4.0.4 on 2022-06-16 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_category_alter_posts_content_alter_posts_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('postid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.posts')),
            ],
        ),
    ]
