# Generated by Django 4.0.4 on 2022-06-30 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0003_review_bqulity_review_vform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/reviews/products'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('max_rate', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('site', models.CharField(max_length=25)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reviews.product')),
            ],
        ),
    ]
