# Generated by Django 4.0.5 on 2022-07-03 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0005_analogy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pox',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Reviews.review',),
        ),
    ]
