# Generated by Django 4.0.4 on 2022-07-03 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0007_delete_pox_rename_pid_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='pid',
            new_name='product',
        ),
    ]
