# Generated by Django 4.0.4 on 2022-06-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='link',
            field=models.CharField(default='www.google.com', max_length=100),
        ),
    ]
